"""commitments and occurrences

Revision ID: 852dd4506ace
Revises: a83ff6d5a534
Create Date: 2026-07-31 00:44:00.971347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '852dd4506ace'
down_revision: Union[str, Sequence[str], None] = 'a83ff6d5a534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commitments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('reminder_days_before', sa.Integer(), nullable=False),
    sa.Column('is_reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("frequency IN ('weekly', 'monthly', 'quarterly', 'yearly', 'oneoff')", name='commitments_frequency_check'),
    sa.CheckConstraint("status IN ('active', 'paused', 'archived')", name='commitments_status_check'),
    sa.CheckConstraint("type IN ('subscription', 'invoice')", name='commitments_type_check'),
    sa.CheckConstraint('amount > 0', name='commitments_amount_check'),
    sa.CheckConstraint('ends_on IS NULL OR ends_on >= starts_on', name='commitments_dates_check'),
    sa.CheckConstraint('reminder_days_before BETWEEN 0 AND 30', name='commitments_reminder_days_check'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commitments_status'), 'commitments', ['status'], unique=False)
    op.create_index(op.f('ix_commitments_type'), 'commitments', ['type'], unique=False)
    op.create_index(op.f('ix_commitments_user_id'), 'commitments', ['user_id'], unique=False)
    op.create_index('ix_commitments_user_status', 'commitments', ['user_id', 'status'], unique=False)
    op.create_table('commitment_occurrences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commitment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'paid', 'skipped')", name='occurrences_status_check'),
    sa.CheckConstraint('amount > 0', name='occurrences_amount_check'),
    sa.ForeignKeyConstraint(['commitment_id'], ['commitments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commitment_id', 'due_date', name='uq_occurrence_commitment_due')
    )
    op.create_index(op.f('ix_commitment_occurrences_commitment_id'), 'commitment_occurrences', ['commitment_id'], unique=False)
    op.create_index(op.f('ix_commitment_occurrences_user_id'), 'commitment_occurrences', ['user_id'], unique=False)
    op.create_index('ix_occurrences_reminder', 'commitment_occurrences', ['due_date'], unique=False, postgresql_where=sa.text("status = 'pending' AND reminder_sent_at IS NULL"))
    op.create_index('ix_occurrences_user_due', 'commitment_occurrences', ['user_id', 'due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_occurrences_user_due', table_name='commitment_occurrences')
    op.drop_index('ix_occurrences_reminder', table_name='commitment_occurrences', postgresql_where=sa.text("status = 'pending' AND reminder_sent_at IS NULL"))
    op.drop_index(op.f('ix_commitment_occurrences_user_id'), table_name='commitment_occurrences')
    op.drop_index(op.f('ix_commitment_occurrences_commitment_id'), table_name='commitment_occurrences')
    op.drop_table('commitment_occurrences')
    op.drop_index('ix_commitments_user_status', table_name='commitments')
    op.drop_index(op.f('ix_commitments_user_id'), table_name='commitments')
    op.drop_index(op.f('ix_commitments_type'), table_name='commitments')
    op.drop_index(op.f('ix_commitments_status'), table_name='commitments')
    op.drop_table('commitments')
    # ### end Alembic commands ###
